=== jeandylan/XmlContactApi/ContactWebService/contactListSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">
    <xs:element name="contactLists">
        <xs:complexType>
            <xs:sequence>
            <xs:element name='contact' type='contactType'
                minOccurs='0' maxOccurs='unbounded' />
            </xs:sequence>
        </xs:complexType>
       </xs:element>
    
    
    <xs:complexType name="contactType">
       
           
        <xs:sequence>
            <xs:element name="id">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[aZ0-zZ9]+"></xs:pattern>
                    </xs:restriction>  
                </xs:simpleType>   
                
            </xs:element>
            <xs:element name="image" type="xs:string" minOccurs="0" maxOccurs="1"/>
            
            <xs:element name="firstName">
             <xs:simpleType>
               <xs:restriction base="xs:string">
                   <xs:pattern value="[A-Z][aA-zZ]+"></xs:pattern>
               </xs:restriction>  
             </xs:simpleType>   
                
            </xs:element>
            <xs:element name="lastName">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[A-Z][aA-zZ]+"></xs:pattern>
                    </xs:restriction>  
                </xs:simpleType> 
                
                
            </xs:element>
            <xs:element name="gender">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="M|F"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="nickName" type="xs:string"/>
            <xs:element name="dateOfBirth" type="xs:date"/>
      
        <xs:element name="postalDetails" maxOccurs="unbounded">
            <xs:complexType>
                <xs:sequence>
                    <xs:element name="city" type="xs:string"/>
                    <xs:element name="street" type="xs:string"/>
                    <xs:element name="postalCode" type="xs:string"/>
                    <xs:element name="country" type="xs:string"/>
                   
                </xs:sequence>
            </xs:complexType>
        </xs:element> 
            <xs:element name="emails">
                <xs:complexType>
                   <xs:sequence>
                     <xs:element name="officeEmail" />
                       <xs:element name="privateEmail"/>
                       
                       
                       
                       
                   </xs:sequence> 
                    
                </xs:complexType>
            </xs:element>
            <xs:element name="telephoneNumbers">
                <xs:complexType>
                    <xs:all>
                        <xs:element name="privateMobile" minOccurs="0" >
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[5]\d{7}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="office" minOccurs="0" >
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="\d{7}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                            
                        </xs:element>
                        
                        
                        
                        
                    </xs:all> 
                    
                </xs:complexType>
            </xs:element>
           
        </xs:sequence>
   
    </xs:complexType>			 
</xs:schema>

=== jeandylan/XmlContactApi/ContactWebService/contactList.xml
<?xml version="1.0" encoding="UTF-8"?>
<contactLists xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contactListSchema.xsd"><contact><id>144525632412</id><image>image/anonymous.png</image><firstName>Dylan</firstName><lastName>Blais</lastName><gender>M</gender><nickName>db</nickName><dateOfBirth>2012-02-02</dateOfBirth><postalDetails><city>Mahebourg</city><street>Rue Boulangerie</street><postalCode>rgregrger</postalCode><country>Mauritius</country></postalDetails><emails><officeEmail>dylan@gmail.com</officeEmail><privateEmail>Blais@you.fr</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>1234567</office></telephoneNumbers></contact><contact><id>144525632466</id><image>image/anonymous.png</image><firstName>Olivier</firstName><lastName>Giroud</lastName><gender>M</gender><nickName>ol</nickName><dateOfBirth>2012-02-02</dateOfBirth><postalDetails><city>Paris</city><street>Rue notre Dame</street><postalCode>rf43ft4</postalCode><country>France</country></postalDetails><emails><officeEmail>olivier@gmail.com</officeEmail><privateEmail>giroud@you.fr</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>1234567</office></telephoneNumbers></contact><contact><id>144596940424</id><image>image/anonymous.png</image><firstName>Theo</firstName><lastName>Walcott</lastName><gender>M</gender><nickName>Theo</nickName><dateOfBirth>2009-12-09</dateOfBirth><postalDetails><city>London</city><street>Mike jagger str</street><postalCode>45454367</postalCode><country>England</country></postalDetails><emails><officeEmail>theo@gmail.com</officeEmail><privateEmail>walcot@arsenal.com</privateEmail></emails><telephoneNumbers><privateMobile>56789012</privateMobile><office>1234567</office></telephoneNumbers></contact><contact><id>144596980323</id><image>image/anonymous.png</image><firstName>Aaroon</firstName><lastName>Ramsey</lastName><gender>M</gender><nickName>Rambo</nickName><dateOfBirth>2001-12-01</dateOfBirth><postalDetails><city>fewf</city><street>erewfe</street><postalCode>123124</postalCode><country>Wales</country></postalDetails><emails><officeEmail>ramsey@yahoo.com</officeEmail><privateEmail>ramsey@arsenal.com</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>1234567</office></telephoneNumbers></contact><contact><id>144597043270</id><image>image/anonymous.png</image><firstName>Bellerin</firstName><lastName>Hector</lastName><gender>M</gender><nickName>Ferari</nickName><dateOfBirth>2004-12-06</dateOfBirth><postalDetails><city>Barcelona</city><street>barcelona Str.</street><postalCode>44343</postalCode><country>Spain</country></postalDetails><emails><officeEmail>bellerin@gmail.com</officeEmail><privateEmail>Hector@arsenal.com</privateEmail></emails><telephoneNumbers><privateMobile>56789012</privateMobile><office>1234678</office></telephoneNumbers></contact><contact><id>14459709488</id><image>image/anonymous.png</image><firstName>Petr</firstName><lastName>Cech</lastName><gender>M</gender><nickName>the wall</nickName><dateOfBirth>2013-03-15</dateOfBirth><postalDetails><city>Mos</city><street>Cheque </street><postalCode>efefe</postalCode><country>USA</country></postalDetails><emails><officeEmail>petr@gmail.com</officeEmail><privateEmail>check@arsenal.com</privateEmail></emails><telephoneNumbers><privateMobile>56787908</privateMobile><office>1234790</office></telephoneNumbers></contact></contactLists>

=== jeandylan/XmlContactApi/ContactWebService/contactList - Copy - Copy.xml
<?xml version="1.0" encoding="UTF-8"?>
<contactLists xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contactListSchema.xsd"><contact><id>140315</id><image>image/sanchez.jpg</image><firstName>Janny</firstName><lastName>Doe</lastName><gender>M</gender><nickName>jD</nickName><dateOfBirth>2002-12-12</dateOfBirth><postalDetails><city>mahe</city><street>rue la hiiix</street><postalCode>uyuiui</postalCode><country>Austrailia</country></postalDetails><emails><officeEmail>dert@yahoo.com</officeEmail><privateEmail>frtyuio@yahoo.com</privateEmail></emails><telephoneNumbers><privateMobile>56782345</privateMobile><office>4535655</office></telephoneNumbers></contact><contact><id>3rfrf</id><image>image/sanchez.jpg</image><firstName>Anneilla</firstName><lastName>Marine</lastName><gender>F</gender><nickName>Ann.Mary</nickName><dateOfBirth>2002-12-12</dateOfBirth><postalDetails><city>paris</city><street>rue la place</street><postalCode>566473few</postalCode><country>Brazil</country></postalDetails><emails><officeEmail>paris@yahoo.com</officeEmail><privateEmail>drake@yahoo.com</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>7654321</office></telephoneNumbers></contact><contact><id>144447983972</id><image>image/download_(2).jpg</image><firstName>Blais</firstName><lastName>Francoise</lastName><gender>F</gender><nickName>fb</nickName><dateOfBirth>2012-12-12</dateOfBirth><postalDetails><city>grand-port/mahebourg</city><street>rue boulangerie ville-noire,mahebourg</street><postalCode>742CU001</postalCode><country>Austrailia</country></postalDetails><emails><officeEmail>dylanblais1@hotmail.com</officeEmail><privateEmail>dylanblais1@hotmail.com</privateEmail></emails><telephoneNumbers><privateMobile>56310814</privateMobile><office>6310814</office></telephoneNumbers></contact><contact><id>144447998052</id><image>image/user_add_man_male_profile_account_person-512.png</image><firstName>Blais</firstName><lastName>Francoise</lastName><gender>M</gender><nickName>DB</nickName><dateOfBirth>2012-12-12</dateOfBirth><postalDetails><city>grand-port/mahebourg</city><street>rue boulangerie ville-noire,mahebourg</street><postalCode>742CU001</postalCode><country>Mauritius</country></postalDetails><emails><officeEmail>dylanblais1@hotmail.com</officeEmail><privateEmail>dylanblais1@hotmail.com</privateEmail></emails><telephoneNumbers><privateMobile>56310814</privateMobile><office>6310814</office></telephoneNumbers></contact><contact><id>144525632316</id><image>image/anonymous.png</image><firstName>Matudi</firstName><lastName>Blaize</lastName><gender>M</gender><nickName>charo</nickName><dateOfBirth>2012-02-02</dateOfBirth><postalDetails><city>Paris</city><street>Rue Margeot</street><postalCode>tt5445654btgr</postalCode><country>France</country></postalDetails><emails><officeEmail>matudi@gmail.com</officeEmail><privateEmail>blaize@you.fr</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>1234567</office></telephoneNumbers></contact><contact><id>144525632412</id><image>image/anonymous.png</image><firstName>Matudi</firstName><lastName>Blaize</lastName><gender>M</gender><nickName>charo</nickName><dateOfBirth>2012-02-02</dateOfBirth><postalDetails><city>Paris</city><street>Rue Margeot</street><postalCode>tt5445654btgr</postalCode><country>France</country></postalDetails><emails><officeEmail>matudi@gmail.com</officeEmail><privateEmail>blaize@you.fr</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>1234567</office></telephoneNumbers></contact><contact><id>144525632466</id><image>image/anonymous.png</image><firstName>Matudi</firstName><lastName>Blaize</lastName><gender>M</gender><nickName>charo</nickName><dateOfBirth>2012-02-02</dateOfBirth><postalDetails><city>Paris</city><street>Rue Margeot</street><postalCode>tt5445654btgr</postalCode><country>France</country></postalDetails><emails><officeEmail>matudi@gmail.com</officeEmail><privateEmail>blaize@you.fr</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>1234567</office></telephoneNumbers></contact><contact><id>144525632473</id><image>image/anonymous.png</image><firstName>Matudi</firstName><lastName>Blaize</lastName><gender>M</gender><nickName>charo</nickName><dateOfBirth>2012-02-02</dateOfBirth><postalDetails><city>Paris</city><street>Rue Margeot</street><postalCode>tt5445654btgr</postalCode><country>France</country></postalDetails><emails><officeEmail>matudi@gmail.com</officeEmail><privateEmail>blaize@you.fr</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>1234567</office></telephoneNumbers></contact><contact><id>144525632449</id><image>image/anonymous.png</image><firstName>Matudi</firstName><lastName>Blaize</lastName><gender>M</gender><nickName>charo</nickName><dateOfBirth>2012-02-02</dateOfBirth><postalDetails><city>Paris</city><street>Rue Margeot</street><postalCode>tt5445654btgr</postalCode><country>France</country></postalDetails><emails><officeEmail>matudi@gmail.com</officeEmail><privateEmail>blaize@you.fr</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>1234567</office></telephoneNumbers></contact><contact><id>144525632492</id><image>image/anonymous.png</image><firstName>Matudi</firstName><lastName>Blaize</lastName><gender>M</gender><nickName>charo</nickName><dateOfBirth>2012-02-02</dateOfBirth><postalDetails><city>Paris</city><street>Rue Margeot</street><postalCode>tt5445654btgr</postalCode><country>France</country></postalDetails><emails><officeEmail>matudi@gmail.com</officeEmail><privateEmail>blaize@you.fr</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>1234567</office></telephoneNumbers></contact><contact><id>144525632590</id><image>image/anonymous.png</image><firstName>Matudi</firstName><lastName>Blaize</lastName><gender>M</gender><nickName>charo</nickName><dateOfBirth>2012-02-02</dateOfBirth><postalDetails><city>Paris</city><street>Rue Margeot</street><postalCode>tt5445654btgr</postalCode><country>France</country></postalDetails><emails><officeEmail>matudi@gmail.com</officeEmail><privateEmail>blaize@you.fr</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>1234567</office></telephoneNumbers></contact><contact><id>144525632589</id><image>image/anonymous.png</image><firstName>Matudi</firstName><lastName>Blaize</lastName><gender>M</gender><nickName>charo</nickName><dateOfBirth>2012-02-02</dateOfBirth><postalDetails><city>Paris</city><street>Rue Margeot</street><postalCode>tt5445654btgr</postalCode><country>France</country></postalDetails><emails><officeEmail>matudi@gmail.com</officeEmail><privateEmail>blaize@you.fr</privateEmail></emails><telephoneNumbers><privateMobile>51234567</privateMobile><office>1234567</office></telephoneNumbers></contact></contactLists>
